apiVersion: v1
kind: Service
metadata:
  name: julia-demos-roadtok8s-com-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      # set targetPort from deployment
      targetPort: julia-demo-port 
  selector:
    app: julia-demos-roadtok8s-com-deployment


